# Site settings
title: The to-be Interhigh Website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio esse consequuntur ipsa quaerat quae, sapiente ullam nesciunt tempora, enim laudantium velit corporis soluta, quisquam facere. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque provident repellat officiis reiciendis animi laborum fugiat esse voluptas incidunt necessitatibus deleniti, quibusdam, ab, labore fuga!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: blahblahblah
github_username:  blahblahblah

# Build settings
markdown: kramdown
