# Site settings
title: InterHigh 
email: info@interhigh.org
description: > # this means to ignore newlines until "baseurl:"
  The awesome web team of Kevin Tham, Tam Nguyen, Steven Hong, Gary Zhao, 
  Brian Choi, Dung Tran, and David Wu are bringing you a brand new site
  for InterHigh!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.interhigh.org"

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/ko
    values:
      layout: default
      lang: ko
  -
    scope:
      path: _posts/zh-CHT
    values:
      layout: default
      lang: zh-CHT

kevin: "boo"
# Nav bar 
navigation_bar_entries:
  - 
    title: "About Us"
    path: "/about/"
  - 
    title: "Photos and Videos"
    path: "/media/"
  - 
    title: "Contact"
    path: "/contact/"